import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'react-tooltip/dist/react-tooltip.css'
import "./globals.css";
import "./build.css";
import { AnimatePresence } from "motion/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kartik's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AnimatePresence mode="wait">

        {
          children
        }
        </AnimatePresence>
      </body>
    </html>
  );
}
